CREATE TABLE "promo_subscriptions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "stripe_checkout_session_id" text NOT NULL,
  "stripe_subscription_id" text,
  "stripe_customer_id" text,
  "stripe_latest_invoice_id" text,
  "customer_email" text NOT NULL,
  "customer_phone" text,
  "pass_holder_name" text,
  "promo_type" text NOT NULL,
  "start_date" timestamp with time zone NOT NULL,
  "trial_start_at" timestamp with time zone NOT NULL,
  "trial_end_at" timestamp with time zone NOT NULL,
  "paid_start_at" timestamp with time zone NOT NULL,
  "paid_end_at" timestamp with time zone NOT NULL,
  "cancel_at" timestamp with time zone NOT NULL,
  "billing_status" text DEFAULT 'checkout_created' NOT NULL,
  "access_status" text DEFAULT 'pending' NOT NULL,
  "passkit_pass_id" text,
  "smart_link_url" text,
  "receipt_url" text,
  "email_trial_sent_at" timestamp with time zone,
  "email_paid_sent_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "promo_subscriptions_stripe_checkout_session_id_unique" UNIQUE("stripe_checkout_session_id"),
  CONSTRAINT "promo_subscriptions_stripe_subscription_id_unique" UNIQUE("stripe_subscription_id"),
  CONSTRAINT "promo_subscriptions_passkit_pass_id_unique" UNIQUE("passkit_pass_id")
);
